
services:
  hsrtech_api: #Api
    image: ${DOCKER_REGISTRY-}hsrtechapi
    build:
      context: .
      dockerfile: src/hsrtech.Api/Dockerfile
    ports: 
     - "8081:8080"

    depends_on:
     - sqlserver

    networks:
     nethsrtech:

#<sqlserver>
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
     - "1433:1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=adminhA@123
     - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql

    networks:
     nethsrtech:
#</sqlserver>

volumes:
  sqlserver_data: {}

networks:
  nethsrtech:
    